Updated init scripts for galaxy to work properly with centos

diff --git a/distro/redhat/etc/rc.d/init.d/galaxy-agent b/distro/redhat/etc/rc.d/init.d/galaxy-agent
--- a/distro/redhat/etc/rc.d/init.d/galaxy-agent
+++ b/distro/redhat/etc/rc.d/init.d/galaxy-agent
@@ -1,36 +1,83 @@
-#!/bin/bash -l
-# chkconfig: 2345 80 90
-# description: Activates/Deactivates Galaxy agent
+#!/bin/sh
+#
+# galaxy-agent - this script starts and stops the galaxy-agent daemon
+#
+# chkconfig:    2345 80 90
+# description:  Activates/Deactivates Galaxy agent
+# processname:  galaxy-agent
+# config:       /etc/galaxy.conf
+#
+# Required-Start:     $remote_fs $syslog
+# Required-Stop:      $remote_fs $syslog
+# Should-Start:       $galaxy-console
+# Should-Stop:        $galaxy-console
+# Default-Start:      2 3 4 5
+# Default-Stop:       0 1 6
+# Short-Description:  Start Galaxy agent.
+# Description:        Start Galaxy agent.
+
+# Source function library.
+. /etc/rc.d/init.d/functions
 
 GALAXY_CONFIG="/etc/galaxy.conf"
 GALAXY_USER=`ruby -ryaml -e "puts YAML.load(File.open('$GALAXY_CONFIG'))['galaxy.agent.user'] || ''"`
 
-if [ -z "$GALAXY_USER" ]
-then
-    echo "Error: Unable to determine galaxy agent user. Please set the galaxy.agent.user property in $GALAXY_CONFIG."
-    exit 2
+galaxy_agent="/usr/bin/galaxy-agent"
+prog=$(basename $galaxy_agent)
+
+start() {
+  echo -n $"Starting Galaxy Agent: "
+  su - $GALAXY_USER -c "$galaxy_agent --start" && success || failure $"$prog start"
+  retval=$?
+  echo
+  return $retval
+}
+
+stop() {
+  echo -n $"Stopping Galaxy Agent: "
+  su - $GALAXY_USER -c "$galaxy_agent --stop" && success || failure $"$prog stop"
+  retval=$?
+  echo
+  return $retval  
+}
+
+restart() {
+  stop
+  sleep 2
+  start
+}
+
+rh_status() {
+  status $prog
+}
+
+rh_status_q() {
+  rh_status >/dev/null 2>&1
+}
+
+if [ -z "$GALAXY_USER" ]; then
+  echo -n "Error: Unable to determine galaxy agent user." && failure
+  echo
+  echo "Please set the \`galaxy.agent.user\` property in $GALAXY_CONFIG."
+  exit 1
 fi
 
 case "$1" in
-'start')
-        logger -p daemon.notice "Starting galaxy-agent"
-        su - $GALAXY_USER -c 'galaxy-agent --start'
-        ;;
-'stop')
-        logger -p daemon.notice "Stopping galaxy-agent"
-        su - $GALAXY_USER -c 'galaxy-agent --stop'
-        ;;
-'restart')
-        logger -p daemon.notice "Restarting galaxy-agent"
-        su - $GALAXY_USER -c 'galaxy-agent --stop'
-        su - $GALAXY_USER -c 'galaxy-agent --start'
-        ;;
-'status') 
-        galaxy-agent --status
-        ;;
-*)
-        echo "Usage: $0 <start|stop|restart|status>"
-        exit 1
-        ;;
+  start)
+      rh_status_q && exit 0
+      $1
+      ;;
+  stop)
+      rh_status_q || exit 0
+      $1
+      ;;
+  restart)
+      $1
+      ;;
+  status|status_q)
+      rh_$1
+      ;;
+  *)
+      echo $"Usage: $0 {start|stop|status|restart}"
+      exit 2
 esac
-
diff --git a/distro/redhat/etc/rc.d/init.d/galaxy-console b/distro/redhat/etc/rc.d/init.d/galaxy-console
--- a/distro/redhat/etc/rc.d/init.d/galaxy-console
+++ b/distro/redhat/etc/rc.d/init.d/galaxy-console
@@ -1,35 +1,82 @@
-#!/bin/bash -l
-# chkconfig: 2345 80 90
-# description: Activates/Deactivates Galaxy console
+#!/bin/sh
+#
+# galaxy-console - this script starts and stops the galaxy-console daemon
+#
+# chkconfig:    2345 80 90
+# description:  Activates/Deactivates Galaxy console
+# processname:  galaxy-console
+# config:       /etc/galaxy.conf
+#
+# Provides:           galaxy-console
+# Required-Start:     $remote_fs $syslog
+# Required-Stop:      $remote_fs $syslog
+# Default-Start:      2 3 4 5
+# Default-Stop:       0 1 6
+# Short-Description:  Start Galaxy console.
+# Description:        Start Galaxy console.
+
+# Source function library.
+. /etc/rc.d/init.d/functions
 
 GALAXY_CONFIG="/etc/galaxy.conf"
 GALAXY_USER=`ruby -ryaml -e "puts YAML.load(File.open('$GALAXY_CONFIG'))['galaxy.console.user'] || ''"`
 
-if [ -z "$GALAXY_USER" ]
-then
-    echo "Error: Unable to determine galaxy console user. Please set the galaxy.console.user property in $GALAXY_CONFIG."
-    exit 2
+galaxy_console="/usr/bin/galaxy-console"
+prog=$(basename $galaxy_console)
+
+start() {
+  echo -n $"Starting Galaxy Console: "
+  su - $GALAXY_USER -c "$galaxy_console --start" && success || failure $"$prog start"
+  retval=$?
+  echo
+  return $retval
+}
+
+stop() {
+  echo -n $"Shutting down Galaxy Console: "
+  su - $GALAXY_USER -c "$galaxy_console --stop" && success || failure $"$prog stop"
+  retval=$?
+  echo
+  return $retval  
+}
+
+restart() {
+  stop
+  sleep 2
+  start
+}
+
+rh_status() {
+  status $prog
+}
+
+rh_status_q() {
+  rh_status >/dev/null 2>&1
+}
+
+if [ -z "$GALAXY_USER" ]; then
+  echo -n "Error: Unable to determine galaxy console user." && failure
+  echo
+  echo "Please set the \`galaxy.console.user\` property in $GALAXY_CONFIG."
+  exit 1
 fi
 
 case "$1" in
-'start')
-        logger -p daemon.notice "Starting galaxy-console"
-        su - $GALAXY_USER -c 'galaxy-console --start'
-        ;;
-'stop')
-        logger -p daemon.notice "Stopping galaxy-console"
-        su - $GALAXY_USER -c 'galaxy-console --stop'
-        ;;
-'restart')
-        logger -p daemon.notice "Restarting galaxy-console"
-        su - $GALAXY_USER -c 'galaxy-console --stop'
-        su - $GALAXY_USER -c 'galaxy-console --start'
-        ;;
-'status') 
-        galaxy-console --status
-        ;;
-*)
-        echo "Usage: $0 <start|stop|restart|status>"
-        exit 1
-        ;;
+  start)
+      rh_status_q && exit 0
+      $1
+      ;;
+  stop)
+      rh_status_q || exit 0
+      $1
+      ;;
+  restart)
+      $1
+      ;;
+  status|status_q)
+      rh_$1
+      ;;
+  *)
+      echo $"Usage: $0 <start|stop|status|restart>"
+      exit 2
 esac
